### ISSUE TITLE
Unable to DEX certain apps from Fugu Marshmallow MMB29V

### ISSUE THREAD

**Issue by mfonville** [JesusFreke/smali#385]
Hi,

when trying to deodex the following APKs from the latest Fugu image ( https://dl.google.com/dl/android/aosp/fugu-mmb29v-factory-2db4c688.tgz )
oat2dex fails at the following apps (that were actually correctly deodexable on the lollipop images):

- app/BugReportSender
- app/NoTouchAuthDelegate
- app/SecondScreenSetup
- app/SecondScreenSetupAuthBridge

**Comment by JesusFreke** [comment]
I don't know anything about "oat2dex". If you're using an unmodified copy of baksmali to deodex, please provide the actual command you used and any output from baksmali.

**Comment by mfonville** [comment]
@JesusFreke I used the fork provided by https://github.com/testwhat/SmaliEx
based on the README.md I thought that the most probable source of the issue could/should be resolved in this codebase. I will try if I can reproduce the issue with the most recent baksmali.

**Comment by mfonville** [comment]
I tried to deodex using baksmali-2.1.2.jar (though I am not very experienced with calling baksmali directly, so I might be making an error myself) it still fails. I was now using the [newest Fugu image MOB30D](https://dl.google.com/dl/android/aosp/fugu-mob30d-factory-551801a2.tgz)

I did run:
`java -jar baksmali-2.1.2.jar -x -d framework/x86/ -d app/BugReportSender/oat/x86/ -c boot.oat:BugReportSender.odex app/BugReportSender/oat/x86/BugReportSender.odex`

and the output is:
```
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lorg/apache/http/client/methods/HttpUriRequest; at index 31
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1794)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1019)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:206)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 84
method: Lcom/x/google/common/io/android/AndroidHttpClient;->toCurl(Lorg/apache/http/client/methods/HttpUriRequest;)Ljava/lang/String;
```

**Comment by JesusFreke** [comment]
Thanks for the details, I was able to reproduce this using the fugu image you mentioned.

Also, You shouldn't need to include the BugReportSender odex in the -c option (but it also shouldn't hurt anything, I don't think)

**Comment by JesusFreke** [comment]
This should be fixed by 9802cf34

**Comment by JesusFreke** [comment]
Nevermind, it looks like some of the other apps you mentioned still have problems. BugReportSender is fixed at least.

**Comment by JesusFreke** [comment]
The remaining issues should be fixed with 93100e57.

**Comment by mfonville** [comment]
Thanks @JesusFreke !
